- id: '1673173451954'
  alias: Doorbell to Alice
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.0x00158d0003a5d05d_lock
    - sensor.0x00158d0003a5d05d_action
    to: doorbell
  condition: []
  action:
  - service: media_player.play_media
    data:
      media_content_type: text
      media_content_id: Звонок в дверь!
      extra:
        volume_level: 0.6
    target:
      device_id:
      - b7ae13cff2fb04a56f1611a7bd9fdb5d
      - e600d40f953494c41ec919d2148fd570
      - 49e5a1a4d554d924f61ecaa8968630bf
      - 644968e9ab73b2930d141deb2aaec43f
      - 37e299b4ee90a2e39ae7e04328439ff4
      - 8883de9fc71bef0b663c61faa4fbefb4
      - f6dbda8398f290149bc8cb48a858452c
  - service: notify.telegram
    data:
      message: Звонок в дверь!
  mode: single
- id: '1694942205257'
  alias: Unavailable entity detection & notification
  description: ''
  use_blueprint:
    path: gmlupatelli/unavailable_entities_notification.yaml
    input:
      actions:
      - service: notify.telegram
        data:
          message: 'У вас есть недоступные устройства: {{entities}}'
          data:
            parse_mode: html
      exclude:
        device_id:
        - fd4ed129390c68716ee6b5ca4ee6abe5
        - a5ddb672314ab72275816e22b91c1e0a
- id: '1696509659566'
  alias: Turn On Mirror When Heater Is On
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 156bb319cb4e575d641e681a1775d672
    entity_id: c3ec9a6bd6247cdf3771e968416f7a1d
    domain: switch
  condition: []
  action:
  - type: turn_on
    device_id: a86a73f9c0cded2becbaea4b58a0c3ca
    entity_id: ca2d574ba695471945a76eb9fbd14f7c
    domain: switch
  mode: single
- id: '1700337065799'
  alias: Turn_on_AC_heater_evening
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: sensor.tag_danil_iphone
    state: mainroom
  action:
  - service: remote.send_command
    target:
      device_id: 3493f23712217b8085d5e05870b37fb4
    data:
      command: power_on
      device: ac
  mode: single
- id: '1700337256838'
  alias: Turn_off_AC_at_morning
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - repeat:
      count: 2
      sequence:
      - data:
          command: power_off_2
          device: ac
        action: remote.send_command
        target:
          device_id: 3493f23712217b8085d5e05870b37fb4
  mode: single
- id: '1703092205692'
  alias: Turn on curtain light when opened
  description: ''
  trigger:
  - platform: device
    device_id: 4b8180d9d908e128920565c0bd31e661
    domain: cover
    entity_id: 03d25d0c4f844c78905fa58906f7a383
    type: opened
  condition: []
  action:
  - type: turn_on
    device_id: b446ed5b21362d52ea95df7a716274cc
    entity_id: 0ff56edad96924c2438d3df1fa7b27f7
    domain: switch
  mode: single
- id: '1703092227298'
  alias: Turn off curtain light when closed
  description: ''
  trigger:
  - platform: device
    device_id: 4b8180d9d908e128920565c0bd31e661
    domain: cover
    entity_id: 03d25d0c4f844c78905fa58906f7a383
    type: closed
  condition: []
  action:
  - type: turn_off
    device_id: b446ed5b21362d52ea95df7a716274cc
    entity_id: 0ff56edad96924c2438d3df1fa7b27f7
    domain: switch
  mode: single
- id: '1703092310991'
  alias: Turn off curtain mainroom light when opened
  description: ''
  trigger:
  - platform: device
    device_id: ea11679f950e59cc987b8cd2b6ff5056
    domain: cover
    entity_id: 6d5198f293f74f55a7c6b97963b1eb38
    type: closed
  condition: []
  action:
  - type: turn_off
    device_id: dced6c6681315aa231b49b28ec1b438f
    entity_id: e9c511738ece30cf4b75c96023ba33ff
    domain: switch
  mode: single
- id: '1703092334996'
  alias: Turn on curtain mainroom light when opened
  description: ''
  trigger:
  - platform: device
    device_id: ea11679f950e59cc987b8cd2b6ff5056
    domain: cover
    entity_id: 6d5198f293f74f55a7c6b97963b1eb38
    type: opened
  condition: []
  action:
  - type: turn_on
    device_id: dced6c6681315aa231b49b28ec1b438f
    entity_id: e9c511738ece30cf4b75c96023ba33ff
    domain: switch
  mode: single
- id: '1706383112067'
  alias: Control Washer+Dishwasher
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.dishwasher
    - switch.washer
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - switch.washer
      - switch.dishwasher
  mode: single
- id: '1722417271264'
  alias: Bath ventilation timer
  description: ''
  trigger:
  - entity_id: fan.ventilation_bath
    for:
      minutes: 15
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: fan.ventilation_bath
    service: homeassistant.turn_off
  mode: single
- id: '1722417292820'
  alias: Shower ventilation timer
  description: ''
  trigger:
  - entity_id: fan.ventilation_shower
    for:
      minutes: 15
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: fan.ventilation_shower
    service: homeassistant.turn_off
  mode: single
- id: '1728058650984'
  alias: Childroom Turn Off Ac in the morning
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - repeat:
      count: 2
      sequence:
      - data:
          command: power_off_2
          device: ac
        action: remote.send_command
        target:
          device_id: d217abb5dd76093411769c4677b6b002
  mode: single
- id: '1728058703218'
  alias: Childroom Turn On Ac in the evening
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: sensor.tag_danil_iphone
    state: mainroom
  action:
  - data:
      command: power_on
      device: ac
    action: remote.send_command
    target:
      device_id: d217abb5dd76093411769c4677b6b002
  mode: single
- id: '1732457430467'
  alias: Limit Kolya Alisa Volume Level
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - media_player.yandex_station_940050344110102101cb
    attribute: volume_level
  conditions: []
  actions:
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.yandex_station_940050344110102101cb
