# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages
  external_url: "https://home-fnv.yandex5.ru"
  internal_url: "http://192.168.1.6:8123"

http:
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 15
  trusted_proxies:
    - 172.19.0.0/24
    - 172.18.0.0/24
    - 192.168.1.0/24

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

