title: Home
views:
type: entities
entities:  
  - entity: switch.dishwasher_power
    type: 'custom:multiple-entity-row'
    name: Dishwasher
    show_state: false
    state_color: true
    secondary_info:
      entity: sensor.dishwasher_operation_state
      name: 'Status:'
    icon: 'mdi:dishwasher'
    entities:
      - entity: sensor.dishwasher_progress
        name: Progress
      - entity: sensor.dishwasher_remaining
        name: Remaining
      - entity: binary_sensor.dishwasher_door
        name: false
        icon: true
        state_color: true
  - entity: switch.water_valve
