#===============================================================================
# Контроллер кондиционера в гостиной
# Wemos D1 mini
#===============================================================================
substitutions:
  node_name: ac_mainroom # Use a unique name.
  node_id: ac_mainroom    # Use a unique id.
  deviceid: ac_mainroom
  devicename: ac_mainroom
  friendly_node_name: "Кондиционер Гостиная"
  device_host: ac-mainroom.lan

#===============================================================================
# Общий конфиг
#===============================================================================
esphome:
  name: ${node_name}
  friendly_name: ${friendly_node_name}

esp8266:
  board: esp12e

web_server:
  port: 80
  auth:
    username: admin
    password: !secret wifi_24_pass

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret api_encryption_key

wifi:
  ssid: !secret wifi_24_name
  password: !secret wifi_24_pass
  use_address: ${device_host}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: !secret esphome_captive_pass

captive_portal:

# Enable logging
logger:
  baud_rate: 0 # disable LOG output on UART as UART is used for Sinclair AC unit
#  level: VERBOSE

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 4800
  parity: EVEN

time:
  - platform: sntp

external_components:
  - source: github://gekkehenkie11/esphome_gree_ac
    components: [sinclair_ac]
    refresh: 0s

climate:
  - platform: sinclair_ac
    name: ${devicename}
    horizontal_swing_select:
      name: ${devicename} Horizontal Swing Mode
    vertical_swing_select:
      name: ${devicename} Vertical Swing Mode
    display_select:
      name: ${devicename} Display Mode
    display_unit_select:
      name: ${devicename} Display Unit
    plasma_switch:
      name: ${devicename} Plasma
    sleep_switch:
      name: ${devicename} Sleep
    xfan_switch:
      name: ${devicename} X-fan
    save_switch:
      name: ${devicename} Save/8 Heat  

button:
  - platform: restart
    name: "Restart"