#################################################
#                WATER                          #
#################################################
mqtt:
  sensor:
    - unique_id: counter_cold
      state_topic: 'home/watercontrol/counter2_1'
      name: 'counter_cold'
      value_template: '{{ (value | float ) }}'
      unit_of_measurement: 'm³'
      device_class: water
      state_class: total_increasing
    - unique_id: counter_hot
      state_topic: 'home/watercontrol/counter2_2'
      name: 'counter_hot'
      value_template: '{{ (value | float ) }}'
      unit_of_measurement: 'm³'
      device_class: water
      state_class: total_increasing
    - unique_id: uptime_watercontrol
      state_topic: 'home/watercontrol/$uptime'
      name: 'uptime_watercontrol'
      value_template: '{{ value | int }}'
  switch:
    - unique_id: water_valve
      name: water_valve
      state_topic: "home/watercontrol/valves"
      command_topic: "home/watercontrol/valves/set"
      payload_on: true
      payload_off: false
      optimistic: false
      retain: false

template:
  sensor:
    - name: counter_hot_outer
      device_class: water
      state_class: total_increasing
      unit_of_measurement: 'm³'
      state: "{{ states('sensor.counter_hot') | float + 88.97 | round(2) }}"
    - name: counter_cold_outer
      device_class: water
      state_class: total_increasing
      unit_of_measurement: 'm³'
      state: "{{ states('sensor.counter_cold') | float + 144.7 | round(2) }}"

  binary_sensor:
    - name: dryer_running
      state: "{{ not is_state('sensor.sushilnaia_mash_dryer_job_state', 'none') }}"
    - name: washer_running
      state: "{{ not is_state('sensor.stiralnaia_mashina_washer_job_state', 'none') }}"

homeassistant:
  customize:
    switch.water_valve:
      friendly_name: Подача воды
    binary_sensor.dryer_running:
      friendly_name: "Сушильная машина"      
    binary_sensor.washer_running:
      friendly_name: "Стиральная машина"

    sensor.counter_hot_outer:
      friendly_name: "Счетчик Внешний Горячая"      
    sensor.counter_cold_outer:
      friendly_name: "Счетчик Внешний Холодная"      
