alarm_control_panel:
  - platform: manual
    name: ha_alarm
    delay_time: 5
    trigger_time: 5
    arming_time: 5

homeassistant:
  customize:
    alarm_control_panel.ha_alarm:
      friendly_name: Охрана